### ISSUE TITLE
TODOs in EDA

### ISSUE THREAD

**Issue by JohnsonChen-id** [parpishro/sugary-beverages-G1#24]
1. Reword EDA intro to include more description of the analysis (Done - Sarah)
2. adjust the boxplot to incorporate bimodality (Done - Sarah)
3. Finish moving the correlation plot into the appendix (Done - Johnson)
4. Modify the Time Series plot to colour code and mention the weekend (Done - Johnson)
5. Reword Missing values & imbalance section (Done - Sarah --> might need to cut down later)
6. Number all figures accordingly (including appendix) (Done - Sarah --> may need to be double checked when FDA is merged)
7. Change wash2 to wash for consistency (Done - Johnson)

**IDEA for EDA:**

1. TimeSeries Plot (Explain Bimodelity of weekday & weekend here) -> 
2. BoxPlot  -> 
3. Missing Data Analysis, plot in appendix -> 
4. Other plot in appendix

**Comment by JohnsonChen-id** [comment]
I think due to the huge difference between weekday sales and weekend sales, we need to differentiate them within boxplots (no outlier would be present if done separately). Since we introduce the concept of bimorality (and we need to write this in time series portion), we need to point it out first before using boxplot, hence time series plot before boxplot.

**Comment by sarahmasri** [comment]
Also might be good to change site names in the dataset to reflect "A, B, C" as indicated in the data (I can do this now)

**Comment by JohnsonChen-id** [comment]
if we are running out of space we can move the whole missing data/imbalance section to the appendix. We can mention missing data in the previous section instead

**Comment by sarahmasri** [comment]
For part 2 (boxplots) - do you mean to change the boxplots to violin plots?

**Comment by JohnsonChen-id** [comment]
> For part 2 (boxplots) - do you mean to change the boxplots to violin plots?

Personally I don't think that's needed as clients may have a hard time understanding that? I was thinking about best case scenario we could represent weekday & weekend distribution separately, The best I can think of is two boxplots maybe one in main report and another in the appendix. If you have any better idea please do!

**Comment by sarahmasri** [comment]
> If you have any better idea please do!

Great, thank you for explaining! Will get on this now :)

**Comment by JohnsonChen-id** [comment]
> Also might be good to change site names in the dataset to reflect "A, B, C" as indicated in the data (I can do this now)

That would be a great idea for consistency

**Comment by JohnsonChen-id** [comment]
All issues within EDA resolved!
